# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: wld ci/cd pipeline website/dev

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - /**
      - .github/workflows/ci-dev-website.yml
  pull_request:
    branches: [ "main" ]
    paths:
      - /**
      - .github/workflows/ci-dev-website.yml

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [20, 22]
    env:
      CI: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}

      - name: Enable core pack
        run: corepack enable

      - name: Install dependencies
        run: |
          yarn install

      - name: Build website
        run: |
          echo "Process.env.CI: $CI" 
          yarn build
