name: wld ci/cd pipeline website/prod

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/ci-prod-website.yml
      - 'src/**'
      - 'package.json'
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/ci-prod-website.yml

#permissions:
#  actions: read       # Allows reading and using actions from GitHub
#  contents: read      # Allows reading the contents of the repository (e.g., code)
#  attestations: write    # Allows uploading artifacts

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: |
          yarn --immutable
          yarn build
